### ISSUE TITLE
[Quais] - UTXO transaction Logic (Change Maker)

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#10]
Requirements:
1. SDK will need to handle the logic for the following
- Fixed denomination math for transactions
- UTXO Fee estimation
- UTXO change output construction
- Input selection
**- When changemaker logic proposes a transaction, it MUST ensure that no inputs are also outputs**

Not sure if these are the same and SDK handles all of this - if not we can split the tasks

As a system, I want to be able to handle UTXO transactions based on a dynamic fee mechanism, so that change can be made when users send transactions.
		A. If a user sends money to another user, and has more than the money that he/she is trying to send + gas fees, the system
		B. Inputs are going to be an array of destination addresses and an amount
		C. Output should be an array of input addresses and an array of output addresses with address and amount per address
		D. That should be passed to the signer which will sign over the array of inputs, and will know how to compose the outputs
		E. Assumption: You have access to the wallet UTXO set which is an array of addresses with an amount per address
		F. If a user can't compose the transaction, throw an error 
			i. There are too many inputs/outputs
                         j. There isn't enough funds

**Comment by rileystephens28** [comment]
### Profile Based Change Maker

In Bitcoin transactions, it is optimal to spend the fewest number of UTXOs in order to have the lowest fee (optimizes for fewest bytes in transaction). This is not the case when spending Qi.

Qi UTXOs should be likened to carrying cash in your wallet. The dilemma here is that generally speaking, there is no ideal spread of bills to carry in your wallet - it varies based on many factors. If you are a shopper planning to buy groceries in cash your desired bill spread differs from the grocery in which you are purchasing from. Simply put, the optimal UTXO set for an individual is dictated by the goals of that individual.

With this in mind @wizeguyy has proposed the idea of optimizing UTXO selection based on different profiles. The `quais` library could support some preconfigured profiles with the ability to add custom profiles at runtime. There is much more flushing out to do regarding implementation details.

cc @DenisIvanov26

**Comment by mibuono** [comment]
Use the biggests to littlest, and make change on the delta.  We can enhance this later.

**Comment by rileystephens28** [comment]
**Example MVP Implementation of Coin Selection Algo**
_This implementation is incomplete and should be used for illustrational purposes only._

```typescript
type UTXO = {
  denomination: number; // Denomination index corresponding to the denominations array
  value: bigint; // Value in Qi, calculated as the denomination's value
};

const denominations: bigint[] = [
  BigInt(1),           // 0.001 Qi
  BigInt(5),           // 0.005 Qi
  BigInt(10),          // 0.01 Qi
  BigInt(50),          // 0.05 Qi
  BigInt(100),         // 0.1 Qi
  BigInt(250),         // 0.25 Qi
  BigInt(500),         // 0.5 Qi
  BigInt(1000),        // 1 Qi
  BigInt(5000),        // 5 Qi
  BigInt(10000),       // 10 Qi
  BigInt(20000),       // 20 Qi
  BigInt(50000),       // 50 Qi
  BigInt(100000),      // 100 Qi
  BigInt(1000000),     // 1000 Qi
  BigInt(10000000),    // 10000 Qi
  BigInt(100000000),   // 100000 Qi
  BigInt(1000000000),  // 1000000 Qi
];

// Function to select UTXOs for a given target amount, considering denominations
function selectUTXOs(targetAmount: bigint, availableUTXOs: UTXO[]): UTXO[] {
  let remainingAmount = targetAmount;
  const selectedUTXOs: UTXO[] = [];

  // Sort available UTXOs by value in descending order to try larger values first
  const sortedUTXOs = availableUTXOs.sort((a, b) => Number(b.value - a.value));

  for (const utxo of sortedUTXOs) {
    if (remainingAmount === BigInt(0)) break; // Stop if we've reached the target amount

    // Check if the UTXO's value is less than or equal to the remaining amount
    if (utxo.value <= remainingAmount) {
      selectedUTXOs.push(utxo);
      remainingAmount -= utxo.value;
    }
  }

  // Check if the selected UTXOs meet the target amount
  if (remainingAmount > BigInt(0)) {
    throw new Error("Unable to select UTXOs to meet the target amount");
  }

  return selectedUTXOs;
}

// Example
const availableUTXOs: UTXO[] = [
  { denomination: 16, value: denominations[16] }, // 1000000 Qi
  { denomination: 8, value: denominations[8] },   // 5 Qi
  { denomination: 0, value: denominations[0] },   // 0.001 Qi
];

const targetAmount = BigInt(10005001); // Target amount in Qi

const selectedUTXOs = selectUTXOs(targetAmount, availableUTXOs);
console.log("Selected UTXOs:", selectedUTXOs.map(utxo => ({ denomination: utxo.denomination, value: utxo.value.toString() })));
```
