### ISSUE TITLE
[Quais] - Support multiple transactions

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#126]
@kiltsonfire please add more context here.

Users should be able to submit more than one transaction in one call.

Right now we use "sendRawTransaction". we should be able to use "sendRawTransactions"

This should be applied for the following:

Multiple Quai transactions
Multiple QI transactions
Multiple Quai and Qi transactions

**Comment by rileystephens28** [comment]
@mibuono I need more context about the purpose of this ticket.

**Comment by mibuono** [comment]
@rileystephens28 more context is above.  I think the use case is basically batching transactions.

**Comment by mibuono** [comment]
This is blocked by GoQuai adding this method to the RPC.
