### ISSUE TITLE
[Quais] - Create Beta Release for internal testing

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#36]
Context Owner: @Juuddi 

Background:
We need to create a beta release when Quais work is nearing golden age features so that Judi and Max can do a delta on what is breaking and create docs for the community.

Some examples of things that might be different:
- Quai and Qi; 
- Methods in Quais will be overloaded (describe overloadings); 
- RPCs are going to have the same overloads; 
- RPC Ports are changing across the board;
- Startup configs are different (no network.env);
- MMTX documentation; 
- How to setup a node (should be simpler); 

Tasks:

- [ ] Package a release
- [ ] Create documentation

**Comment by robertlincecum** [comment]
blocked until all wanted PR's are merged in @rileystephens28
