### ISSUE TITLE
[Quais] - Get Balance Support for UTXO (Qi)

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#44]
This will require adding getQiBalance to the methods switch case in JsonRpcApiProvider.getRpcRequest()

AbstractProvider.getBalance(address: AddressLike, blockTag?: BlockTag): Promise<bigint>
This existing abstract provider method must be modified to check if the address is a qi or quai address and call the correct get balance function. If quai address use the getBalance method and if qi address use getQiBalance. Need to confirm that the getBalance method was not overloaded to support qi addresses as well.

Note:  Confirmed - this method will be overloaded.  There may be not a lot of work here and we might be able to use the getbalance method as the Qi balance is overloaded.

**Comment by rileystephens28** [comment]
There is no direct work that needs to be done related to getting Qi balance, however, we do need to add the `formatEther` counterpart `formatQi` to properly convert to decimal value of Qi since Qi and Quai use different significant digit requirements.
