### ISSUE TITLE
[Quais] - Strip out all logic that does not apply unused code

### ISSUE THREAD

**Issue by rileystephens28** [dominant-strategies/quais.js#80]
There is a lot of code from the ethers library that does not apply to quai network. An example of this is ENS support. 

The motivation for this is because we have to get a security audit done on quais and the audit pricing is by lines of code reviewed. There is the added benefit of removing bloat and making things clearer.

**Comment by DenisIvanov26** [comment]
Features to delete due to no functionality in Quai yet:
- ENS
- CCIP
- IBAN / ICAP address resolution
