### ISSUE TITLE
[Quais] - Musig Integration + Signatures with musig

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#9]
Requirements:

1. Find a mu sig implementation and import the library
2. Provide mu sig transaction signing

**Comment by rileystephens28** [comment]
Check out [this](https://github.com/wangshouh/musig) library

**Comment by rileystephens28** [comment]
The purpose of the Musig integration is to create an aggregated key signature to include in a Qi transaction that spends multiple UTXOs. The outline below describe the steps for creating an unsigned transaction followed by the steps to correctly sign it.

**Steps for creating an unsigned Qi transaction**

1. Use coin selection algorithm to determine transaction inputs (a set of unspent transaction outputs to be spent) and outputs (a new set unspent transaction outputs to create, including any change to return to sender).
2. Gather the public and private key pairs that own the UTXOs included in the transaction inputs
3. Ensure the length of the public and private key arrays are equal (throw a validation error if they are not)
4. Create a transaction object with the validated transaction inputs and outputs

**Steps for signing the transactions using [musig-js](https://github.com/reardencode/musig-js/tree/master) library)**

1. Get the hash the unsigned transaction object
2. If there is only one private key, the transaction hash is signed directly using this key. This will be a single key Schnorr signature.
3. If there are multiple private keys, we have to use aggregated signature, starting by using the `keyAgg` function to aggregate the public keys of all signers. This function takes an array of public keys and optional tweaks, returning a `KeyGenContext` object representing the aggregated key.
4. Each signer generates their nonce pair using the `nonceGen` function. This function requires the signer's secret key, public key, and the message to be signed, among other parameters. It returns a public nonce that will be shared with other signers.
5. Once all signers have generated and shared their public nonces, use the `nonceAgg` function to aggregate these nonces into a single aggregate public nonce. This function takes an array of public nonces from all signers.
6. With the aggregate public nonce and the message hash, each signer starts a signing session using the `startSigningSession` function. This function requires the aggregate nonce, the message to be signed, the array of public keys, and any tweaks. It returns a `SessionKey` object for use in the next steps.
7. Each signer generates a partial signature using the `partialSign` function. This function requires the signer's secret key, their public nonce, and the `SessionKey` object from the previous step. It returns a partial signature.
8. Optionally, each signer can verify other signers' partial signatures using the `partialVerify` function. This step ensures that each partial signature is valid before proceeding to signature aggregation. This function requires the partial signature, the message hash, the signer's public key, the signer's public nonce, and the `SessionKey` object.
9. Once all partial signatures are collected and optionally verified, use the `signAgg` function to aggregate these partial signatures into a final signature. This function takes an array of partial signatures and the `SessionKey` object, returning the aggregated signature.

**Sample Implementation Using [musig-js](https://github.com/reardencode/musig-js/tree/master) library**
_Not a complete implementation, it is only for illustrational purposes._

```typescript
type TransactionInput = {
  txhash: Uint8Array;
  index: number;
  pubkey: Uint8Array;
};

type TransactionOutput = {
  denomination: number;
  address: Uint8Array;
};

type UTXOTransaction = {
  chainId: bigint;
  inputs: TransactionInput[];
  outputs: TransactionOutput[];
  signature?: Uint8Array; // Optional until signed
};

const musig: MuSig = new MuSigImplementation();

function createUTXOTransaction(
  chainId: bigint,
  inputs: TransactionInput[],
  outputs: TransactionOutput[]
): UTXOTransaction {
  return {
    chainId,
    inputs,
    outputs,
  };
}

async function signTransaction(
  transaction: UTXOTransaction,
  privateKeys: Uint8Array[]
): Promise<UTXOTransaction> {
  // Create a hash of the transaction for signing
  const transactionHash = hashTransaction(transaction);

  // Check if there is only one private key
  if (privateKeys.length === 1) {
      // Single key scenario: Perform a simple Schnorr signature
      const publicKey = musig.getPublicKey(privateKeys[0]);
      const signature = schnorr.sign(transactionHash, privateKeys[0], publicKey); // can use @noble library for this

      // Attach the signature to the transaction
      transaction.signature = signature;
   } else {
     // Multiple keys scenario: Proceed with aggregated signature process

    // Generate public keys from private keys
    const publicKeys = privateKeys.map(sk => musig.getPublicKey(sk));

    // Aggregate public keys
    const aggPublicKey = musig.aggregatePublicKeys(publicKeys);

    // Each signer generates a nonce pair
    const nonces = privateKeys.map(sk => musig.generateNoncePair(sk));

    // Aggregate nonces
    const aggNonce = musig.aggregateNonces(nonces.map(n => n.publicNonce));

    // Each signer creates a partial signature
    const partialSignatures = privateKeys.map((sk, index) =>
      musig.partialSign({
        secretKey: sk,
        publicNonce: nonces[index].publicNonce,
        aggNonce,
        aggPublicKey,
        message: transactionHash,
      })
    );

    // Aggregate the partial signatures into a final signature
    const finalSignature = musig.aggregateSignatures(partialSignatures);

    // Attach the aggregated signature to the transaction
    transaction.signature = finalSignature;
  }
  return transaction;
}

// call createUTXOTransaction to create a UTXO transaction
// pass the newly created transaction and private keys of UTXO owning addresses to signTransaction
```
